name: Build and Deploy Next.js to Azure on Push

on:
  push:
    branches:
      - main  # Adjust to your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: <your_registry_name>.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t <your_registry_name>.azurecr.io/nextjs-app:${{ github.sha }} .
          docker push <your_registry_name>.azurecr.io/nextjs-app:${{ github.sha }}

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nextjs-frontend-app'  # Azure App Service name
          images: '<your_registry_name>.azurecr.io/nextjs-app:${{ github.sha }}'
