name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build Docker image
        run: |
          docker build . -t nestapp

      - name: Push Docker image to ACR
        run: |
          az acr login --name nestapp
          docker tag nestapp:latest nestapp.azurecr.io/nestapp:latest
          docker push nestapp.azurecr.io/nestapp:latest

      - name: Deploy to Azure App Service
        run: |
          az webapp config container set \
            --name <your-app-service-name> \
            --resource-group user-app-api_group \
            --docker-custom-image-name nestapp.azurecr.io/nestapp:latest \
            --docker-registry-server-url https://nestapp.azurecr.io \
            --docker-registry-server-user ${{ secrets.AZURE_CLIENT_ID }} \
            --docker-registry-server-password ${{ secrets.AZURE_CLIENT_SECRET }}
